version: '2'
services:
  kibana:
          build: .
          volumes:
                  - "/home/thomas/Documents/BigData/punch/kibana.yml:/usr/share/kibana/config/kibana.yml"
          links:
                  - "elastic:elasticsearch"
          ports:
                  - "5601:5601"

  elastic:
          image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
          container_name: elastic
          environment:
                  - "discovery.type=single-node"
          ulimits:
                  memlock:
                          soft: -1
                          hard: -1
          ports:
                  - "9200:9200"
                  - "9300:9300"
                                                                                                                             
